### ISSUE TITLE
Error Packet has error bit set 

### ISSUE THREAD

**Issue by agamm** [tahnok/colmi_r02_client#24]
```
C:\Users\MyUser>colmi_r02_client.exe --address=31:38:42:35:XX:XX get-real-time-heart-rate
Starting reading, please wait.
asyncio: Exception in callback Client._handle_tx(<bleak.backen...001820F1A0C80>)(bytearray(b'\...\x00\x00\x8c'))
handle: <Handle Client._handle_tx(<bleak.backen...001820F1A0C80>)(bytearray(b'\...\x00\x00\x8c'))>
Traceback (most recent call last):
  File "C:\Users\MyUser\.pyenv\pyenv-win\versions\3.12.7\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\MyUser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\client.py", line 106, in _handle_tx
    assert packet_type < 127, f"Packet has error bit set {packet}"
```
OS: Windows
Python: 3.12.7
`XX:XX` was changed.

Any ideas?

**Comment by tahnok** [comment]
Can you try again with the --record flag and the --debug flag and upload the log and the recording?

**Comment by agamm** [comment]
Here:

colmi_r02_client.exe --record --debug --address=31:38:42:35:XX:XX get-real-time-heart-rate
colmi_r02_client.cli: Recording responses to captures\colmi_response_capture_1730404231.bin
colmi_r02_client.client: Connecting to 31:38:42:35:XX:XX
colmi_r02_client.client: Connected!
Starting reading, please wait.
colmi_r02_client.client: Sending packet: bytearray(b'i\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j')
colmi_r02_client.client: Received packet bytearray(b'i\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j')
colmi_r02_client.client: Sending packet: bytearray(b'\x1e3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Q')
colmi_r02_client.client: Received packet bytearray(b'\x9e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8c')
asyncio: Exception in callback Client._handle_tx(<bleak.backen...001F9B00C2DB0>)(bytearray(b'\...\x00\x00\x8c'))
handle: <Handle Client._handle_tx(<bleak.backen...001F9B00C2DB0>)(bytearray(b'\...\x00\x00\x8c'))>
Traceback (most recent call last):
  File "C:\Users\MyUser\.pyenv\pyenv-win\versions\3.12.7\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\MyUser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\client.py", line 106, in _handle_tx
    assert packet_type < 127, f"Packet has error bit set {packet}"
           ^^^^^^^^^^^^^^^^^
           
bin capture file:
> i
![image](https://github.com/user-attachments/assets/113cb90f-c137-4333-bdf5-1cae8cd5e8ff)

**Comment by tahnok** [comment]
Is this the r10?

**Comment by agamm** [comment]
No, I bought this:
https://www.aliexpress[.]us/item/3256806445134241.html

**Comment by devwearsprada** [comment]
I have the same issue with a COLMI R02 ring. Below the logs and bin file. 

Output of `scan`:
```
                Name  | Address
--------------------------------------------
            R02_5001  |  C77FF180-C50B-DFD0-AAC1-XXXXXXXXXXXX
```

Output of `get-real-time-heart-rate`

```
colmi_r02_client --address=C77FF180-C50B-DFD0-AAC1-E8AC2CA17F1D --debug --record get-real-time-heart-rate >> log.txt
colmi_r02_client.cli: Recording responses to captures/colmi_response_capture_1730818479.bin
colmi_r02_client.client: Connecting to C77FF180-C50B-DFD0-AAC1-E8AC2CA17F1D
colmi_r02_client.client: Connected!
colmi_r02_client.client: Sending packet: bytearray(b'i\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j')
colmi_r02_client.client: Received packet bytearray(b'i\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j')
colmi_r02_client.client: Sending packet: bytearray(b'\x1e3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Q')
colmi_r02_client.client: Received packet bytearray(b'\x9e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8c')
asyncio: Exception in callback PeripheralDelegate.did_update_value_for_characteristic()
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic()>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/colmi-r02-client/lib/python3.13/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 381, in did_update_value_for_characteristic
    notify_callback(bytearray(value))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/pipx/venvs/colmi-r02-client/lib/python3.13/site-packages/colmi_r02_client/client.py", line 106, in _handle_tx
    assert packet_type < 127, f"Packet has error bit set {packet}"
           ^^^^^^^^^^^^^^^^^
AssertionError: Packet has error bit set bytearray(b'\x9e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8c')
```

`.bin` file of `record`

[colmi_response_capture_1730817364.bin.zip](https://github.com/user-attachments/files/17634380/colmi_response_capture_1730817364.bin.zip)

**Comment by agamm** [comment]
@tahnok anything else we can try to debug this?

**Comment by tahnok** [comment]
I haven't had a chance to look at this yet, but I will when I get the chance. On discord I've had a report that maybe it's a different chip but same protocol (implemented slightly differently)

**Comment by tahnok** [comment]
I think I fixed this, can you try again?

**Comment by agamm** [comment]
Now I get:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MyUser\.local\bin\colmi_r02_client.exe\__main__.py", line 4, in <module>
  File "C:\Users\MyUser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\cli.py", line 16, in <module>
    from colmi_r02_client.client import Client
  File "C:\Users\MyUser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\client.py", line 13, in <module>
    from colmi_r02_client import battery, date_utils, steps, set_time, blink_twice, hr, hr_settings, packet, reboot, real_time
  File "C:\Users\MyUser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\date_utils.py", line 4, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'

```

**Comment by tahnok** [comment]
Oops, different issue introduced recently that I just now fixed if you want to try again

**Comment by agamm** [comment]
```
colmi_r02_util.exe scan
Found device(s)
                Name  | Address
--------------------------------------------
```

empty.

**Comment by tahnok** [comment]
Scanning shouldn't have changed, you might have to try a few times to pick it up, it seems the scan misses the device. Can you try `colmi_r02_client --address=YOUR_ADDRESS get-real-time heart-rate`?

**Comment by Colinwehrhan** [comment]
Hmmm I'm still getting this error, any idea what it was?

I have used pipx to get newest packages and updated firmware through the qRing app. Like others in this thread my scan is spotty and rarely finds the ring

**Comment by Colinwehrhan** [comment]
Oddly now it is erroring but showing the heart rate data at end. Connection still very spotty

Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\myuser\pipx\venvs\colmi-r02-client\Lib\site-packages\colmi_r02_client\client.py", line 104, in _handle_tx
    assert packet_type < 127, f"Packet has error bit set {packet}"
AssertionError: Packet has error bit set bytearray(b'\x9e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8c')
[65, 66, 66, 67, 67, 68]
