### ISSUE TITLE
Extra packets received with Real-Time HR request

### ISSUE THREAD

**Issue by cyrilzakka** [tahnok/colmi_r02_client#27]
After requesting heart rate, I am getting some unhandled packets which don't seem to correspond to anything I've seen in the documentation. Have you encountered these before?
```
Got readings: [84, 84, 84, 84, 84, 83, 83]
Write to characteristic successful
Received packet with command: 106
Full packet: 6a01000000000000000000000000006b
Unhandled packet type: 106
Received packet with command: 67
Full packet: 43f0070100000000000000000000003b
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43241105240007a5052801ce00000049
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43241105280107fd016f004900000063
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43241105300207af00250019000000a3
Unhandled packet type: 67
Received packet with command: 67
Full packet: 432411053403071c13b003bb0200005a
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43241105380407f0017e004700000076
Unhandled packet type: 67
Received packet with command: 67
Full packet: 432411053c05076c068401eb000000a7
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43241105400607e403e1008e00000020
Unhandled packet type: 67
Received packet with command: 67
Full packet: 43f00a0100000000000000000000003e
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110424000a4803bc007800000029
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110428010ae60b5902b4010000b0
Unhandled packet type: 67
Received packet with command: 67
Full packet: 432411042c020a46142b04e402000023
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110430030a4e0fd4022f0200001d
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110434040a4915f1030a0300001d
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110438050a381b1b05e20300001b
Unhandled packet type: 67
Received packet with command: 67
Full packet: 432411043c060a22181c05740300009a
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110450070a6d03bc007d00000086
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110454080a3704ea009a000000a1
Unhandled packet type: 67
Received packet with command: 67
Full packet: 4324110458090a2d03b400740000003f
Unhandled packet type: 67
Received packet with command: 72
Full packet: 4800084f000000018cca0005ab0035db
Unhandled packet type: 72
```

**Comment by felixalguzman** [comment]
me too, my device is recognized as R02_6501

```bash
asyncio: Exception in callback PeripheralDelegate.did_update_value_for_characteristic()
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic()>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixdev/.local/pipx/venvs/colmi-r02-client/lib/python3.13/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 381, in did_update_value_for_characteristic
    notify_callback(bytearray(value))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/felixdev/.local/pipx/venvs/colmi-r02-client/lib/python3.13/site-packages/colmi_r02_client/client.py", line 106, in _handle_tx
    assert packet_type < 127, f"Packet has error bit set {packet}"
           ^^^^^^^^^^^^^^^^^
AssertionError: Packet has error bit set bytearray(b'\x9e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8c')

[93, 93, 93, 92, 92, 91]
```
